### ISSUE TITLE
Lit Review

### ISSUE THREAD

**Issue by jacobdanovitch** [amandaLi7/HTUI#9]
* [ ] Previous CHI papers (#5)
* [ ] Lit review tools (#6)
* [ ] Graph exploration tools (#8)
